# Generated by Django 4.1.7 on 2024-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("unset", "Unset"),
                ],
                default="unset",
                max_length=20,
            ),
        ),
    ]
