version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/develop/Dockerfile
    container_name: school_tracker_develop
    ports: 
      - "8000:8000"
    env_file: 
      - ./.envs/.develop/.django
    depends_on: 
      - db

  db:
    image: postgres:13
    container_name: postgres_develop
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.develop/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
