# Generated by Django 4.1.7 on 2024-10-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="child",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_students",
                to="members.group",
            ),
        ),
        migrations.CreateModel(
            name="AssignedTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("support", "Support")],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_teachers",
                        to="members.group",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.teacher",
                    ),
                ),
            ],
        ),
    ]
