# Generated by Django 5.1.3 on 2024-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_remove_group_teacher_alter_child_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="child",
        ),
        migrations.AddField(
            model_name="child",
            name="parents",
            field=models.ManyToManyField(related_name="children", to="members.parent"),
        ),
    ]
