# Generated by Django 4.1.7 on 2024-10-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_remove_group_teacher_alter_child_group_and_more"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayplan",
            name="behaviour",
            field=models.CharField(
                choices=[
                    ("great_day", "Great Day"),
                    ("ok_day", "Ok Day"),
                    ("might_be_better", "Might Be Better"),
                    ("talk_needed", "Talk Needed"),
                    ("not_specified", "Not Specified"),
                ],
                default="not_specified",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dayplan",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dayplans",
                to="members.child",
            ),
        ),
        migrations.AlterField(
            model_name="dayplan",
            name="meals_at_school",
            field=models.CharField(
                choices=[
                    ("full", "Full"),
                    ("half", "Half"),
                    ("little", "Little"),
                    ("not_specified", "Not Specified"),
                    ("important_note", "Important Note"),
                ],
                default="not_specified",
                max_length=20,
            ),
        ),
    ]
